@startuml

class ru.nsu.ga.grentseva.pizzeria.config.BakerConfig {
- int cookTime
+ int getCookTime()
}

class ru.nsu.ga.grentseva.pizzeria.storage.OrderQueue {
- Queue<Order> queue
- boolean closed
+ void addOrder(Order)
+ Order getOrder()
+ void close()
}

interface ru.nsu.ga.grentseva.pizzeria.storage.OrderSource {
~ void addOrder(Order)
~ Order getOrder()
~ void close()
}

class ru.nsu.ga.grentseva.pizzeria.ordermodel.Order {
- int id
- OrderStatus status
+ int getId()
+ void setStatus(OrderStatus)
- void printStatus()
+ String toString()
}

class ru.nsu.ga.grentseva.pizzeria.workers.Courier {
- int capacity
- int deliveryTime
- Storage storage
+ void run()
}

class ru.nsu.ga.grentseva.pizzeria.util.Logger {
+ {static} void log(String)
}

class ru.nsu.ga.grentseva.pizzeria.config.CourierConfig {
- int capacity
- int deliveryTime
+ int getCapacity()
+ int getDeliveryTime()
}

class ru.nsu.ga.grentseva.pizzeria.Pizzeria {
- OrderSource orderSource
- Storage storage
- List<Baker> bakers
- List<Courier> couriers
- int workingTime
+ void start()
}

class ru.nsu.ga.grentseva.pizzeria.Main {
+ {static} void main(String[])
}

interface ru.nsu.ga.grentseva.pizzeria.storage.Storage {
~ void put(Order)
~ List<Order> take(int)
~ void close()
}

class ru.nsu.ga.grentseva.pizzeria.config.Config {
- int warehouseCapacity
- int workingTime
- List<BakerConfig> bakers
- List<CourierConfig> couriers
+ int getWarehouseCapacity()
+ int getWorkingTime()
+ List<BakerConfig> getBakers()
+ List<CourierConfig> getCouriers()
}

class ru.nsu.ga.grentseva.pizzeria.config.ConfigLoader {
+ {static} Config load(String)
}

class ru.nsu.ga.grentseva.pizzeria.storage.Warehouse {
- int capacity
- List<Order> pizzas
- boolean closed
+ void put(Order)
+ List<Order> take(int)
+ void close()
}

abstract class ru.nsu.ga.grentseva.pizzeria.workers.Worker {
# int id
+ String toString()
}

enum ru.nsu.ga.grentseva.pizzeria.ordermodel.OrderStatus {
NEW
COOKING
COOKED
STORED
DELIVERING
DELIVERED
}

class ru.nsu.ga.grentseva.pizzeria.workers.Baker {
- int cookTime
- OrderSource orderSource
- Storage storage
+ void run()
}

' inheritance
java.lang.Thread <|-- ru.nsu.ga.grentseva.pizzeria.workers.Worker
ru.nsu.ga.grentseva.pizzeria.workers.Worker <|-- ru.nsu.ga.grentseva.pizzeria.workers.Baker
ru.nsu.ga.grentseva.pizzeria.workers.Worker <|-- ru.nsu.ga.grentseva.pizzeria.workers.Courier

' interfaces
ru.nsu.ga.grentseva.pizzeria.storage.OrderSource <|.. ru.nsu.ga.grentseva.pizzeria.storage.OrderQueue
ru.nsu.ga.grentseva.pizzeria.storage.Storage <|.. ru.nsu.ga.grentseva.pizzeria.storage.Warehouse

' associations
ru.nsu.ga.grentseva.pizzeria.workers.Baker --> ru.nsu.ga.grentseva.pizzeria.storage.OrderSource
ru.nsu.ga.grentseva.pizzeria.workers.Baker --> ru.nsu.ga.grentseva.pizzeria.storage.Storage

ru.nsu.ga.grentseva.pizzeria.workers.Courier --> ru.nsu.ga.grentseva.pizzeria.storage.Storage

ru.nsu.ga.grentseva.pizzeria.storage.Warehouse --> ru.nsu.ga.grentseva.pizzeria.ordermodel.Order
ru.nsu.ga.grentseva.pizzeria.storage.OrderQueue --> ru.nsu.ga.grentseva.pizzeria.ordermodel.Order

ru.nsu.ga.grentseva.pizzeria.ordermodel.Order --> ru.nsu.ga.grentseva.pizzeria.ordermodel.OrderStatus

' config relations
ru.nsu.ga.grentseva.pizzeria.config.Config --> ru.nsu.ga.grentseva.pizzeria.config.BakerConfig
ru.nsu.ga.grentseva.pizzeria.config.Config --> ru.nsu.ga.grentseva.pizzeria.config.CourierConfig

ru.nsu.ga.grentseva.pizzeria.config.ConfigLoader --> ru.nsu.ga.grentseva.pizzeria.config.Config

' main relations
ru.nsu.ga.grentseva.pizzeria.Main --> ru.nsu.ga.grentseva.pizzeria.config.ConfigLoader
ru.nsu.ga.grentseva.pizzeria.Main --> ru.nsu.ga.grentseva.pizzeria.Pizzeria

ru.nsu.ga.grentseva.pizzeria.Pizzeria --> ru.nsu.ga.grentseva.pizzeria.storage.OrderSource
ru.nsu.ga.grentseva.pizzeria.Pizzeria --> ru.nsu.ga.grentseva.pizzeria.storage.Storage
ru.nsu.ga.grentseva.pizzeria.Pizzeria o-- ru.nsu.ga.grentseva.pizzeria.workers.Baker
ru.nsu.ga.grentseva.pizzeria.Pizzeria o-- ru.nsu.ga.grentseva.pizzeria.workers.Courier

@enduml